# *Introduction to Pandas*

## What is pandas  ?

*Pandas is a powerful Python library used for data analysis and data manipulation.
It is mainly used to easily handle tabular data (rows and columns), such as data from Excel files, CSV files, and databases*

## Installation of Pandas

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

*pip is used in Python to install, update, and remove libraries (packages).*

##### **pip:** Package manager
##### **install:** To install a new package
##### **pandas:** Name of the library

## Import Pandas library

In [2]:
import pandas as pd

##### **import:** A keyword used to bring a library or module into Python
##### **pandas:** A Python library used for data analysis and data handling
##### **as:** Means alias (a short name)
##### **pd:** A short form (alias) for pandas

## Data structures
##### **Series :-** *1-D data (single column)*
##### **DataFrame :-** *2-D data (rows + columns)*

 **Series:** A Series is like a single column that contains values along with their index.

### Simple Series

In [3]:
data = [10, 20, 30, 40]
j = pd.Series(data)
print(j)

0    10
1    20
2    30
3    40
dtype: int64

### Custom Index ke saath Series

In [4]:
data= [10,20,30,40,50]                     
a= pd.Series(data, index = ['a','b','c','d','e'])
print(a)

a    10
b    20
c    30
d    40
e    50
dtype: int64

### Dictionary se Series

In [5]:
data = {"Math": 85, "Science": 90, "English": 78}
j = pd.Series(data)
print(j)

Math       85
Science    90
English    78
dtype: int64

## operations
#### Arithmetic Operations(add,Subtract,Multiply)
#### Series vs Series Operations
#### Built-in Functions (Stats)
#### modify karna

In [6]:
a = pd.Series([10, 20, 30])
print(a + 5)

0    15
1    25
2    35
dtype: int64

In [12]:
a = pd.Series([10, 20, 30])
print(a - 5)

0     5
1    15
2    25
dtype: int64

In [14]:
a = pd.Series([10, 20, 30])
print(a * 5)

0     50
1    100
2    150
dtype: int64

### Series vs Series Operations

In [17]:
s1 = pd.Series([10, 20, 30])
s2 = pd.Series([1, 2, 3])
print(s1 + s2)

0    11
1    22
2    33
dtype: int64

### Comparison Operations

In [18]:
data = [10, 20, 30, 40]
s = pd.Series(data)
print(s)
print(s > 15)

0    10
1    20
2    30
3    40
dtype: int64
0    False
1     True
2     True
3     True
dtype: bool

### Built-in Functions

In [19]:
data= [10,20,30,40,50]                     
a= pd.Series(data, index = ['a','b','c','d','e'])
print(a)
print(a.sum())    # total
print(a.mean())   # average
print(a.max())    # maximum
print(a.min())    # minimum

a    10
b    20
c    30
d    40
e    50
dtype: int64
150
30.0
50
10

### modify karna

In [20]:
s = pd.Series([10, 20, 30], index=["a", "b", "c"])
s['b']= 200
print(s)

a     10
b    200
c     30
dtype: int64

### DataFrame

**DataFrame:** *A DataFrame is like a table or an Excel sheet that contains rows and columns, and each column has a name.*

In [21]:
import numpy as np

**import numpy as np:** The NumPy library is used in the program because **np.nan** is used.
**np.nan** means a missing value or an empty value.

In [22]:
data = {
    "Name": ["Jatin", "aman", "Neha","ayush","abhi","aman","varun"],
    "Age": [22, 24, 21, np.nan, 25, 24, 20 ],
    "Marks": [85, 90, np.nan, 82, 91, 90,83]
}
df = pd.DataFrame(data)
print(df)

    Name   Age  Marks
0  Jatin  22.0   85.0
1   aman  24.0   90.0
2   Neha  21.0    NaN
3  ayush   NaN   82.0
4   abhi  25.0   91.0
5   aman  24.0   90.0
6  varun  20.0   83.0

Ek variable me dictionary {} ke form me data store kiya , Us dictionary ko **pd.DataFrame()** me pass karke pandas DataFrame banya.,pandas automatic index karaga

In [24]:
df['rollno']=[101,102,103,104,105,102,107]         
print(df)

    Name   Age  Marks  rollno
0  Jatin  22.0   85.0     101
1   aman  24.0   90.0     102
2   Neha  21.0    NaN     103
3  ayush   NaN   82.0     104
4   abhi  25.0   91.0     105
5   aman  24.0   90.0     102
6  varun  20.0   83.0     107

To add a new column to an existing DataFrame, we use
**df["new_column"] = value**.

In [25]:
df.head()

    Name   Age  Marks  rollno
0  Jatin  22.0   85.0     101
1   aman  24.0   90.0     102
2   Neha  21.0    NaN     103
3  ayush   NaN   82.0     104
4   abhi  25.0   91.0     105

**df.head():** It shows the first 5 rows of the data.

In [27]:
df.tail()

    Name   Age  Marks  rollno
2   Neha  21.0    NaN     103
3  ayush   NaN   82.0     104
4   abhi  25.0   91.0     105
5   aman  24.0   90.0     102
6  varun  20.0   83.0     107

**df.tail:-** Ye data ke last (aakhri) 5 rows ko show karta hai.

In [28]:
df.sample()

    Name   Age  Marks  rollno
6  varun  20.0   83.0     107

**df.sample():** It shows one random row from the data.

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Age     6 non-null      float64
 2   Marks   6 non-null      float64
 3   rollno  7 non-null      int64
dtypes: float64(2), int64(1), object(1)
memory usage: 356.0+ bytes

**df.info():** It shows information about the data types of the data.

In [30]:
df.isnull()

    Name    Age  Marks  rollno
0  False  False  False   False
1  False  False  False   False
2  False  False   True   False
3  False   True  False   False
4  False  False  False   False
5  False  False  False   False
6  False  False  False   False

**df.isnull():** It shows missing values as `True` and filled (non-missing) values as `False` in the data.

In [31]:
df.isnull().sum()

Name      0
Age       1
Marks     1
rollno    0
dtype: int64

**df.isnull().sum():** It shows the number of missing values in each column.

In [32]:
# df.fillna(method=("ffill"),inplace=True)

**df.fillna:** It is used to fill missing data.

In [33]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
dtype: bool

**df.duplicated():** It shows duplicate data as `True` and the remaining (unique) data as `False`.

In [34]:
df.duplicated().sum()

np.int64(1)

**df.duplicated().sum():** It is used to get the total count of duplicate rows in the DataFrame.

In [35]:
df.drop_duplicates(inplace= True)

**df.drop_duplicates(inplace=True):** It is used to delete duplicate rows from the data.

In [36]:
print(df.describe())

             Age      Marks      rollno
count   5.000000   5.000000    6.000000
mean   22.400000  86.200000  103.666667
std     2.073644   4.086563    2.160247
min    20.000000  82.000000  101.000000
25%    21.000000  83.000000  102.250000
50%    22.000000  85.000000  103.500000
75%    24.000000  90.000000  104.750000
max    25.000000  91.000000  107.000000

**print(df.describe()):** It is used to show summary statistics of the numeric columns in a DataFrame, such as count, mean, standard deviation (std), minimum (min), 25%, 50%, 75% percentiles, and maximum (max).

In [37]:
df.nunique()

Name      6
Age       5
Marks     5
rollno    6
dtype: int64

**df.nunique():** It is used to get the count of unique (distinct) values in each column.

In [38]:
df['rollno']=pd.to_datetime(df['rollno'],errors="coerce")

**pd.to_datetime:** It is used to convert the `'rollno'` column to datetime format, and if any value cannot be converted, it is assigned as `NaT` (Not a Time).

## upload csv file

In [39]:
a=pd.read_csv("netflix_titles.csv")
a.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

**Read a CSV file:-** To read a CSV file into a pandas DataFrame, we use pd.read_csv().
Replace **filename.csv** with the exact path or name of your file.

In [40]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [41]:
a.columns = a.columns.str.strip()

In [42]:
a.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [43]:
a['date_added']=pd.to_datetime(a['date_added'],errors="coerce")

In [44]:
duration_split = a['duration'].str.extract(r'(\d+)\s*(\w+)')            ## Regular expressions (regex) are a powerful tool for extracting specific patterns from text data.
a['duration_num'] = pd.to_numeric(duration_split[0],errors ='coerce')
a['duration_unit']=duration_split[1]

In [45]:
a.isnull().sum()

show_id             0
type                0
title               0
director         2634
cast              825
country           831
date_added         98
release_year        0
rating              4
duration            3
listed_in           0
description         0
duration_num        3
duration_unit       3
dtype: int64

In [46]:
a['duration_unit'].value_counts()

duration_unit
min        6128
Season     1793
Seasons     883
Name: count, dtype: int64

In [47]:
a['duration_unit'] = a['duration_unit'].replace({'Seasons': 'Season'})

In [48]:
a['duration_unit'].value_counts()

duration_unit
min       6128
Season    2676
Name: count, dtype: int64

In [49]:
a['duration_num'] = a.groupby('duration_unit')['duration_num'].transform(lambda x: x.fillna(x.median()))   #missingnvalue (nan) ko fill karna

In [50]:
# df.groupby('duration_unit') --> sab rows ko unke duration_unit ke hisaab se group karo. season group, min group
#  ['duration_num'] -- means group ke andar sirf number column.
# The transform() function in pandas is a powerful tool that allows you to apply a function to each element of a DataFrame or Series,
# returning a result with the same shape as the original data. 
# This is particularly useful when you need to apply a transformation function 
# that returns a result for each element while maintaining the structure (rows and indexes) of the original DataFrame.
###############################################################################################

# import pandas as pd

# t = pd.DataFrame({'A': [1, 2, 3, 4], 'B': [5, 6, 7, 8]})
# t['A_transformed'] = t['A'].transform(lambda x: x * 2)
# t['B_transformed'] = t['B'].transform(lambda x: x * 2)
# print(t)

In [51]:
a.loc[a['duration'].isna() & (a['type'] == 'Movies'),'duration_unit '] ='min'
# Jitni rows me duration missing (NaN) hai, Aur type = Movie hai Un rows ke duration_unit me 'min' fill kar do
a.loc[a['duration'].isna() & (a['type'] == 'TV Show'),'duration_unit '] ='season'

# loc[] = label-based selection -> Rows ko condition se select karta hai, Aur un rows me kisi column ki value change ya read kar sakte ho.
# df.loc[df['age'] > 18, 'status'] = 'Adult'
# isna() = checks missing values (NaN, empty) -> give result in True or False

In [52]:
a.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,duration_num,duration_unit,duration_unit
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",90.0,min,NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2.0,Season,NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,1.0,Season,NaN
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",1.0,Season,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2.0,Season,NaN

In [53]:
a = a.drop(columns=['duration'])

In [54]:
a.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,listed_in,description,duration_num,duration_unit,duration_unit
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,R,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",158.0,min,NaN
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,2019-07-01,2018,TV-Y7,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",2.0,Season,NaN
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2019-11-01,2009,R,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,88.0,min,NaN
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,PG,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",88.0,min,NaN
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,111.0,min,NaN

In [55]:
# # # # # # Option A — Fill missing with "Unknown"
# # # # # df['rating'] = df['rating'].fillna('Unknown')
# # # # Option B — Fill missing with mode (most common rating)
# # # most_common = df['rating'].mode()[0]
# # # df['rating'] = df['rating'].fillna(most_common)
# # Option C — Create a “missing flag” + fill (BEST for ML)
# df['rating_missing'] = df['rating'].isna().astype(int)
# df['rating'] = df['rating'].fillna('Unknown')

In [56]:
a['rating_missing'] = a['rating'].isna().astype(int)  # True-1 , False-0
a['rating'] = a['rating'].fillna('Unknown')

# df['rating_missing'] = df['rating'].isna().astype(int) , # True-1 , False-0
# df['rating'] = df['rating'].fillna('Unknown')

In [57]:
a.isnull().sum()

show_id              0
type                 0
title                0
director          2634
cast               825
country            831
date_added          98
release_year         0
rating               0
listed_in            0
description          0
duration_num         3
duration_unit        3
duration_unit     8807
rating_missing       0
dtype: int64

In [58]:
a.duplicated().sum()

np.int64(0)

In [59]:
median_date = a['date_added'].median()
a['date_added'] =a['date_added'].fillna(median_date)

In [60]:
a.isnull().sum()

show_id              0
type                 0
title                0
director          2634
cast               825
country            831
date_added           0
release_year         0
rating               0
listed_in            0
description          0
duration_num         3
duration_unit        3
duration_unit     8807
rating_missing       0
dtype: int64

In [61]:
a['country_missing'] = a['country'].isna().astype(int)
a['country'] = a['country'].fillna("Unknown")

In [62]:
a.isnull().sum()

show_id               0
type                  0
title                 0
director           2634
cast                825
country               0
date_added            0
release_year          0
rating                0
listed_in             0
description           0
duration_num          3
duration_unit         3
duration_unit      8807
rating_missing        0
country_missing       0
dtype: int64

In [63]:
a['director_missing'] = a['director'].isna().astype(int)  # True - 1 , False - 0
a['cast_missing'] = a['cast'].isna().astype(int)

In [64]:
a['director'] = a['director'].fillna("Unknown")
a['cast'] = a['cast'].fillna("Unknown")
a['duration_unit'] = a['duration_unit'].fillna("Unknown")

In [65]:
a['duration_num'] = a['duration_num'].fillna("Unknown")

In [66]:
a.isnull().sum()

show_id                0
type                   0
title                  0
director               0
cast                   0
country                0
date_added             0
release_year           0
rating                 0
listed_in              0
description            0
duration_num           0
duration_unit          0
duration_unit       8807
rating_missing         0
country_missing        0
director_missing       0
cast_missing           0
dtype: int64

In [67]:
# a['duration_num'] = a.groupby('duration_unit')['duration_num'].transform(lambda x: x.fillna(x.median()))

In [68]:
a.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,listed_in,description,duration_num,duration_unit,duration_unit,rating_missing,country_missing,director_missing,cast_missing
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,Documentaries,"As her father nears the end of his life, filmm...",90.0,min,NaN,0,0,0,1
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2.0,Season,NaN,0,0,1,0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,1.0,Season,NaN,0,1,0,0
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",1.0,Season,NaN,0,1,1,1
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2.0,Season,NaN,0,0,1,0

In [69]:
a.to_csv("cleaned_netflix.csv",index= False)

* **a:** A DataFrame in pandas that stores your data in table form. This will contain your cleaned or processed data.
* **to_csv():** A pandas function used to save a DataFrame as a CSV file.
* **"cleaned_netflix.csv":** The name of the CSV file. A new CSV file with this name will be created. If a file with the same name already exists, it will be overwritten.
* **index=False:** By default, pandas saves the DataFrame’s index (0, 1, 2, …) in the file. `index=False` means do **not** save the index in the CSV file.

## Try these 4 question

* Pandas use karke ek DataFrame banao jisme ye data ho: hint :- pd.DataFrame()
    * Name,Age,Marks.
* DataFrame me:
   * missing value (NaN) ko Age ka mean se fill karo hint :-isna() / fillna()
   * sirf un students ko print karo jinke Marks ≥ 85 hint :-conditional filtering
* Ek naya column banao:
  * Result → agar Marks ≥ 80 ho to "Pass" warna "Fail" hint:- np.where() ya apply()
* DataFrame ko Marks ke descending order me sort karo. hint:-dataFrame ko Marks ke descending order me shint